apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: digital-twin
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: digital-twin
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: "lykart/hackaton-front:nginx-prod"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]